name: SACHIE KOBAYASHI

description: Composer/作曲家

avatar: https://raw.githubusercontent.com/kbys88/kbys88.github.io/main/images/sachiehome1.png
favicon: https://raw.githubusercontent.com/kbys88/kbys88.github.io/main/images/favi.ico

navigation:
  - name: Top
    url: /
  - name: Bio
    url: /bio
  - name: Sound
    url: /sound
  - name: Works
    url: /works
  - name: Pic
    url: /pic
  - name: Lesson
    url: /teach
    group: secondary
  - name: Blog
    url: /dansunrecoindecemonde
  - name: STUDIO
    url: /cucurbits
    group: secondary

paginate: 8

footer-links:
  email: info@sachiekobayashi.com
  instagram: sachie_kbys_comp
  youtube:

footer-text: Copyright (c) 2025 Sachie Kobayashi

google_analytics:

url: "https://kbys88.github.io"

permalink: /:title/
paginate_path: /page:num/

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded
  sass_dir: _sass

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

excerpt_separator: ---

future: true
